"""create table

Revision ID: 58169330756b
Revises: 
Create Date: 2024-11-25 23:07:13.855597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58169330756b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_date', sa.Date(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('declared_cost', sa.Numeric(scale=2), nullable=False),
    sa.Column('insurance_cost', sa.Numeric(scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_date', sa.Date(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff')
    op.drop_table('insurance')
    # ### end Alembic commands ###
