"""fix type colomn

Revision ID: 95b13a94da29
Revises: 968296b28007
Create Date: 2024-11-25 20:27:26.675547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b13a94da29'
down_revision: Union[str, None] = '968296b28007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurance_costs', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(scale=2),
               existing_nullable=False)
    op.alter_column('tariff', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tariff', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('insurance_costs', 'price',
               existing_type=sa.Numeric(scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
