"""create table insurence costs

Revision ID: 968296b28007
Revises: 9d6bfba4c06d
Create Date: 2024-11-25 02:38:47.191099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968296b28007'
down_revision: Union[str, None] = '9d6bfba4c06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_date', sa.Date(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_costs')
    # ### end Alembic commands ###
